<a href="https://colab.research.google.com/github/Emi123Johnson/Data-Science/blob/main/exp1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
print(x.shape)

(4,)


In [7]:
y=np.array([[1,2],[3,4]])

y=np.array([[1,2],[3,4]])

In [9]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [11]:
z=np.array([[1+0.j,2+5.j]])

In [12]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [13]:
a=np.zeros((2,3))

In [14]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(a.shape)

(2, 3)


In [16]:
b=np.ones((2,3),dtype=int)

In [17]:
print(b)

[[1 1 1]
 [1 1 1]]


In [19]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
e=np.arange(10)

In [21]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
e=np.arange(12,21)
print(e)

[12 13 14 15 16 17 18 19 20]


In [29]:
e=np.arange(5,20,3)

In [30]:
print(e)

[ 5  8 11 14 17]


In [33]:
f=np.linspace(1,20,7)

In [34]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [35]:
g=np.random.random((3,4))

In [36]:
print(g)

[[0.54017156 0.74687669 0.43195618 0.96414134]
 [0.67211507 0.34830573 0.82903134 0.22185913]
 [0.25874396 0.08970982 0.36748781 0.70310895]]


In [37]:
h=np.random.random((3,4))

In [39]:
print(h.reshape(2,2,3))
                 
                 
                 
                 
                 
                 
                 
                 
                 

[[[0.14895751 0.15807714 0.36863243]
  [0.87785781 0.43677718 0.47209664]]

 [[0.28434913 0.08651856 0.42835628]
  [0.47679267 0.88652492 0.27594024]]]


In [40]:
x=np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [41]:
print(x[-1])

11


In [42]:
x.resize(3,4)
print(x)
print(x[-1,-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11


In [43]:
print(x[2][3])

11


In [44]:
y=np.arange(1,26)
print(y)
print(y[3:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [45]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [46]:
print(y[10:15])

[11 12 13 14 15]


In [47]:
print(y[-5:])

[21 22 23 24 25]


In [48]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [49]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [50]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [51]:
y=y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [53]:
y=y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [54]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [55]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [56]:
print(y[:,-1])

[ 5 10 15 20 25]


In [57]:
print(y[:,-1])

[ 5 10 15 20 25]


In [58]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [59]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [60]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [61]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [62]:
print(a>3)

[False False False  True  True]


In [65]:
a=np.arange(0,4).reshape((2,2 ))

In [66]:
b=np.eye(2)

In [67]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [68]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [70]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
print(x.sum())

45


In [72]:
print(x.sum(axis=0))

[12 15 18]


In [73]:
print(x.sum(axis=1))

[ 6 15 24]


In [74]:
print(x.sum(axis=1))

[ 6 15 24]


In [75]:
x = np.arange(1,10).reshape(3,3)

In [76]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [79]:
print(x.max(axis=0))

[7 8 9]


In [80]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
